channels:
- conda-forge
dependencies:
- python=3.9.15
- pip<=22.2.2
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==0.24.2
  - typing-extensions==4.3.0
name: mlflow-env
